schema_version: 1

context:
  name: django-hitcount
  version: 1.3.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django-hitcount-${{ version }}.tar.gz
  sha256: 5fe70720a75e49bfcee5c4312a7df989bb9e22848039bba1de4406f96fb9cf4d

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - django-etc >=1.2.0

tests:
  - python:
      imports:
        - hitcount
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Hit counting application for Django.
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/thornomad/django-hitcount

extra:
  recipe-maintainers:
    - rxm7706
